project:
  type: website
  output-dir: _site

website:
  title: "Ruowei Li"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: posts/index.qmd
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/RuoWei-ctrl

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
